run-name: docker

on: workflow_dispatch

jobs:
  build:
    name: build dist
    permissions:
      contents: read
      id-token: write
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2
        with: 
          ref: main

      - uses: actions/setup-node@v4.1.0
        with:
          node-version: 20

      - uses: pnpm/action-setup@v4.0.0
        with:
          version: 9

      - name: build dist
      - run: |
          pnpm i
          npm run build
          ls

      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: dist

  build-docker:
    name: build-docker

    permissions:
      contents: read
      pages: write
      id-token: write

    runs-on: ubuntu-latest
    needs: build-docker

    steps:
      - name: Download dist artifact
        uses: actions/download-artifact@v4
        with:
          name: dist-artifact
      - name: Check dist content
        run: ls -al dist/



    
        

    

