run-name: docker

on: workflow_dispatch

jobs:
  build:
    name: build dist
    permissions:
      contents: read
      id-token: write
    
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4.2.2
        with: 
          ref: main

      - name: setup-node
        uses: actions/setup-node@v4.1.0
        with:
          node-version: 20
      - name: setup-pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          version: 9

      - name: build dist
        run: |
          pnpm i
          npm run build

      - name: Build Docker Image
        run: |
          docker build -t dockertest:latest .

      - name: Log in to ALIYUN
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.ALIYUN_DOCKER_USERNAME }}
          password: ${{ secrets.ALIYUN_DOCKER_USERNAME }}

      - name: push docker image
        run: |
          docker push ${{vars.REGISTRY_MIRROR}}/${{vars.REGISTRY_NAMESPACE}}/${{vars.APP_NAME}}:latest

        

    

